const API_BASE_URL_DEVELOPMENT = 'https://localhost:7160/api/v1';
const API_BASE_URL_PRODUCTION = '';

const TOP_CIDADES = 3;

const ENDPOINTS = {
    GET_CIDADES: 'cidades',
    GET_PREVISOES_CIDADES_MAIS_FRIAS: `previsoes/frias`,
    GET_PREVISOES_CIDADES_MAIS_QUENTES: `previsoes/quentes`
}

const development = {
    API_URL_GET_CIDADES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CIDADES}`,
    API_URL_GET_PREVISAO_CIDADE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CIDADES}`,
    API_URL_GET_PREVISOES_CIDADES_MAIS_FRIAS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PREVISOES_CIDADES_MAIS_FRIAS}?top=${TOP_CIDADES}`,
    API_URL_GET_PREVISOES_CIDADES_MAIS_QUENTES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PREVISOES_CIDADES_MAIS_QUENTES}?top=${TOP_CIDADES}`,
}

const production = {
    API_URL_GET_CIDADES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CIDADES}`,
    API_URL_GET_PREVISAO_CIDADE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CIDADES}`,
    API_URL_GET_PREVISOES_CIDADES_MAIS_FRIAS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PREVISOES_CIDADES_MAIS_FRIAS}?top=${TOP_CIDADES}`,
    API_URL_GET_PREVISOES_CIDADES_MAIS_QUENTES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PREVISOES_CIDADES_MAIS_QUENTES}?top=${TOP_CIDADES}`,
}

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
